name: Release Assets

on:
  release:
    types: [published]

jobs:
  upload-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare tarballs
        shell: bash
        run: |
          set -euo pipefail
          TAG="${{ github.event.release.tag_name }}"
          VERSION="${TAG#v}"
          DIST="/tmp/grail-dist"
          rm -rf "$DIST" && mkdir -p "$DIST/payload" "$DIST/out"
          tar -czf "$DIST/payload.tar.gz" \
            --exclude-vcs --exclude=node_modules \
            -C . \
            cli daemon scripts package.json package-lock.json README.md LICENSE GRAIL_INIT.md
          for os in linux darwin; do \
            for arch in x64 arm64; do \
              cp "$DIST/payload.tar.gz" "$DIST/out/grail-v${VERSION}-${os}-${arch}.tar.gz"; \
            done; \
          done
          ls -l "$DIST/out"
      - name: Upload to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="${{ github.event.release.tag_name }}"
          gh release upload "$TAG" /tmp/grail-dist/out/grail-v${TAG#v}-*.tar.gz --clobber

